name: mandatory tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make
    - name: cd ft_printf_tests
      run: cd ft_printf_tests
    - name: sh test m
      run: sh test m
