name: mandatory tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: mandatory tests
      run: ls -lR; make; cd ./tester; make; sh test m
      shell: bash
